import type {
  ComplexPluginDefinition,
  PluginLocalMaterialSettingsAdapterContract,
} from '@/features/plugins/complexPluginContracts';
import { ANYCUBIC_PLUGIN_MANIFEST } from './pluginManifest';
import { ANYCUBIC_AFF_FORMAT_DEFINITION } from './slicing/affFormatDefinition';
import { ANYCUBIC_AZF_FORMAT_DEFINITION } from './slicing/azfFormatDefinition';

// ─── Local material settings adapter (shared by AZF and AFF) ────────

const ANYCUBIC_MATERIAL_SETTINGS_BASE = {
  displayName: 'Anycubic Resin Settings',
  replacesDefaultMaterialSettings: true,
  tabs: [
    { id: 'simple', title: 'Simple', order: 10 },
    { id: 'twostage', title: 'Advanced', order: 20 },
  ],
  sections: [
    { id: 'layers-exposure', title: 'Layers and Exposure', tabId: 'simple', order: 10 },
    { id: 'print-control', title: 'Print Control', tabId: 'simple', order: 20 },
    { id: 'layers-exposure-ts', title: 'Layers and Exposure', tabId: 'twostage', order: 10 },
    { id: 'normal-layers', title: 'Normal Layers Control', tabId: 'twostage', order: 20 },
    { id: 'bottom-layers', title: 'Bottom Layers Control', tabId: 'twostage', order: 30 },
  ],
  cards: [
    { id: 'layers-exposure-card', title: 'Layers and Exposure', tabId: 'simple', sectionId: 'layers-exposure', order: 10 },
    { id: 'print-control-card', title: 'Print Control', tabId: 'simple', sectionId: 'print-control', order: 10 },
    { id: 'layers-exposure-ts-card', title: 'Layers and Exposure', tabId: 'twostage', sectionId: 'layers-exposure-ts', order: 10 },
    { id: 'normal-layers-card', title: 'Normal Layers Control', tabId: 'twostage', sectionId: 'normal-layers', order: 10 },
    { id: 'bottom-layers-card', title: 'Bottom Layers Control', tabId: 'twostage', sectionId: 'bottom-layers', order: 10 },
  ],
  fields: [
    // ── Layers and Exposure (simple tab) ──────────────────────────
    {
      key: 'layerHeightMm',
      label: 'Layer Thickness (mm)',
      kind: 'number' as const,
      defaultValue: 0.05,
      min: 0.001,
      max: 1,
      step: 0.001,
      placement: { tabId: 'simple', sectionId: 'layers-exposure', cardId: 'layers-exposure-card', order: 10 },
      metadataPath: 'material.layerHeightMm',
    },
    {
      key: 'normalExposureSec',
      label: 'Normal Exposure Time (s)',
      kind: 'number' as const,
      defaultValue: 2.0,
      min: 0,
      max: 300,
      step: 0.001,
      placement: { tabId: 'simple', sectionId: 'layers-exposure', cardId: 'layers-exposure-card', order: 20 },
      metadataPath: 'material.normalExposureSec',
    },
    {
      key: 'waitTimeBeforeCureSec',
      label: 'Off Time (s)',
      kind: 'number' as const,
      defaultValue: 1.0,
      min: 0,
      max: 120,
      step: 0.001,
      placement: { tabId: 'simple', sectionId: 'layers-exposure', cardId: 'layers-exposure-card', order: 30 },
      metadataPath: 'material.waitTimeBeforeCureSec',
    },
    {
      key: 'bottomExposureSec',
      label: 'Bottom Exposure Time (s)',
      kind: 'number' as const,
      defaultValue: 45.0,
      min: 0,
      max: 300,
      step: 0.001,
      placement: { tabId: 'simple', sectionId: 'layers-exposure', cardId: 'layers-exposure-card', order: 40 },
      metadataPath: 'material.bottomExposureSec',
    },
    {
      key: 'bottomLayerCount',
      label: 'Bottom Layers',
      kind: 'integer' as const,
      defaultValue: 5,
      min: 0,
      max: 200,
      step: 1,
      placement: { tabId: 'simple', sectionId: 'layers-exposure', cardId: 'layers-exposure-card', order: 50 },
      metadataPath: 'material.bottomLayerCount',
    },
    {
      key: 'transitionLayerCount',
      label: 'Transition Layer Count',
      kind: 'integer' as const,
      defaultValue: 15,
      min: 0,
      max: 100000,
      step: 1,
      placement: { tabId: 'simple', sectionId: 'layers-exposure', cardId: 'layers-exposure-card', order: 60 },
      metadataPath: 'material.transitionLayerCount',
    },

    // ── Print Control (simple tab) ────────────────────────────────
    {
      key: 'liftDistanceMm',
      label: 'Z Lift Distance (mm)',
      kind: 'number' as const,
      defaultValue: 5.0,
      min: 0,
      max: 50,
      step: 0.001,
      placement: { tabId: 'simple', sectionId: 'print-control', cardId: 'print-control-card', order: 10 },
      metadataPath: 'material.liftDistanceMm',
    },
    {
      key: 'liftSpeedMmMin',
      label: 'Z Lift Speed (mm/min)',
      kind: 'number' as const,
      defaultValue: 120,
      min: 0,
      max: 100000,
      step: 1,
      placement: { tabId: 'simple', sectionId: 'print-control', cardId: 'print-control-card', order: 20 },
      metadataPath: 'material.liftSpeedMmMin',
    },
    {
      key: 'retractSpeedMmMin',
      label: 'Z Retract Speed (mm/min)',
      kind: 'number' as const,
      defaultValue: 120,
      min: 0,
      max: 100000,
      step: 1,
      placement: { tabId: 'simple', sectionId: 'print-control', cardId: 'print-control-card', order: 30 },
      metadataPath: 'material.retractSpeedMmMin',
    },

    // ── Layers and Exposure (twostage tab, same fields) ──────────
    {
      key: 'layerHeightMm',
      label: 'Layer Thickness (mm)',
      kind: 'number' as const,
      defaultValue: 0.05,
      min: 0.001,
      max: 1,
      step: 0.001,
      placement: { tabId: 'twostage', sectionId: 'layers-exposure-ts', cardId: 'layers-exposure-ts-card', order: 10 },
      metadataPath: 'material.layerHeightMm',
    },
    {
      key: 'normalExposureSec',
      label: 'Normal Exposure Time (s)',
      kind: 'number' as const,
      defaultValue: 2.0,
      min: 0,
      max: 300,
      step: 0.001,
      placement: { tabId: 'twostage', sectionId: 'layers-exposure-ts', cardId: 'layers-exposure-ts-card', order: 20 },
      metadataPath: 'material.normalExposureSec',
    },
    {
      key: 'waitTimeBeforeCureSec',
      label: 'Off Time (s)',
      kind: 'number' as const,
      defaultValue: 1.0,
      min: 0,
      max: 120,
      step: 0.001,
      placement: { tabId: 'twostage', sectionId: 'layers-exposure-ts', cardId: 'layers-exposure-ts-card', order: 30 },
      metadataPath: 'material.waitTimeBeforeCureSec',
    },
    {
      key: 'bottomExposureSec',
      label: 'Bottom Exposure Time (s)',
      kind: 'number' as const,
      defaultValue: 45.0,
      min: 0,
      max: 300,
      step: 0.001,
      placement: { tabId: 'twostage', sectionId: 'layers-exposure-ts', cardId: 'layers-exposure-ts-card', order: 40 },
      metadataPath: 'material.bottomExposureSec',
    },
    {
      key: 'bottomLayerCount',
      label: 'Bottom Layers',
      kind: 'integer' as const,
      defaultValue: 5,
      min: 0,
      max: 200,
      step: 1,
      placement: { tabId: 'twostage', sectionId: 'layers-exposure-ts', cardId: 'layers-exposure-ts-card', order: 50 },
      metadataPath: 'material.bottomLayerCount',
    },
    {
      key: 'transitionLayerCount',
      label: 'Transition Layer Count',
      kind: 'integer' as const,
      defaultValue: 15,
      min: 0,
      max: 100000,
      step: 1,
      placement: { tabId: 'twostage', sectionId: 'layers-exposure-ts', cardId: 'layers-exposure-ts-card', order: 60 },
      metadataPath: 'material.transitionLayerCount',
    },

    // ── Normal Layers Control (twostage tab) ─────────────────────
    {
      key: 'liftDistanceMm',
      label: 'Z Lift Distance (mm)',
      kind: 'number' as const,
      defaultValue: 3.0,
      splitWithKey: 'liftDistance2Mm',
      min: 0,
      max: 50,
      step: 0.001,
      placement: { tabId: 'twostage', sectionId: 'normal-layers', cardId: 'normal-layers-card', order: 10 },
      metadataPath: 'material.liftDistanceMm',
    },
    {
      key: 'liftDistance2Mm',
      label: 'Z Lift Distance Step 2 (mm)',
      kind: 'number' as const,
      defaultValue: 5.0,
      min: 0,
      max: 50,
      step: 0.001,
      placement: { tabId: 'twostage', sectionId: 'normal-layers', cardId: 'normal-layers-card', order: 11 },
      metadataPath: 'material.liftDistance2Mm',
    },
    {
      key: 'liftSpeedMmMin',
      label: 'Z Lift Speed (mm/min)',
      kind: 'number' as const,
      defaultValue: 120,
      splitWithKey: 'liftSpeed2MmMin',
      min: 0,
      max: 100000,
      step: 1,
      placement: { tabId: 'twostage', sectionId: 'normal-layers', cardId: 'normal-layers-card', order: 20 },
      metadataPath: 'material.liftSpeedMmMin',
    },
    {
      key: 'liftSpeed2MmMin',
      label: 'Z Lift Speed Step 2 (mm/min)',
      kind: 'number' as const,
      defaultValue: 360,
      min: 0,
      max: 100000,
      step: 1,
      placement: { tabId: 'twostage', sectionId: 'normal-layers', cardId: 'normal-layers-card', order: 21 },
      metadataPath: 'material.liftSpeed2MmMin',
    },
    {
      key: 'retractSpeed2MmMin',
      label: 'Z Retract Speed (mm/min)',
      kind: 'number' as const,
      defaultValue: 360,
      splitWithKey: 'retractSpeedMmMin',
      min: 0,
      max: 100000,
      step: 1,
      placement: { tabId: 'twostage', sectionId: 'normal-layers', cardId: 'normal-layers-card', order: 30 },
      metadataPath: 'material.retractSpeed2MmMin',
    },
    {
      key: 'retractSpeedMmMin',
      label: 'Z Retract Speed Step 2 (mm/min)',
      kind: 'number' as const,
      defaultValue: 120,
      min: 0,
      max: 100000,
      step: 1,
      placement: { tabId: 'twostage', sectionId: 'normal-layers', cardId: 'normal-layers-card', order: 31 },
      metadataPath: 'material.retractSpeedMmMin',
    },

    // ── Bottom Layers Control (twostage tab) ─────────────────────
    {
      key: 'bottomLiftDistanceMm',
      label: 'Z Lift Distance (mm)',
      kind: 'number' as const,
      defaultValue: 5.0,
      splitWithKey: 'bottomLiftDistance2Mm',
      min: 0,
      max: 50,
      step: 0.001,
      placement: { tabId: 'twostage', sectionId: 'bottom-layers', cardId: 'bottom-layers-card', order: 10 },
      metadataPath: 'material.bottomLiftDistanceMm',
    },
    {
      key: 'bottomLiftDistance2Mm',
      label: 'Z Lift Distance Step 2 (mm)',
      kind: 'number' as const,
      defaultValue: 3.0,
      min: 0,
      max: 50,
      step: 0.001,
      placement: { tabId: 'twostage', sectionId: 'bottom-layers', cardId: 'bottom-layers-card', order: 11 },
      metadataPath: 'material.bottomLiftDistance2Mm',
    },
    {
      key: 'bottomLiftSpeedMmMin',
      label: 'Z Lift Speed (mm/min)',
      kind: 'number' as const,
      defaultValue: 120,
      splitWithKey: 'bottomLiftSpeed2MmMin',
      min: 0,
      max: 100000,
      step: 1,
      placement: { tabId: 'twostage', sectionId: 'bottom-layers', cardId: 'bottom-layers-card', order: 20 },
      metadataPath: 'material.bottomLiftSpeedMmMin',
    },
    {
      key: 'bottomLiftSpeed2MmMin',
      label: 'Z Lift Speed Step 2 (mm/min)',
      kind: 'number' as const,
      defaultValue: 180,
      min: 0,
      max: 100000,
      step: 1,
      placement: { tabId: 'twostage', sectionId: 'bottom-layers', cardId: 'bottom-layers-card', order: 21 },
      metadataPath: 'material.bottomLiftSpeed2MmMin',
    },
    {
      key: 'bottomRetractSpeed2MmMin',
      label: 'Z Retract Speed (mm/min)',
      kind: 'number' as const,
      defaultValue: 240,
      splitWithKey: 'bottomRetractSpeedMmMin',
      min: 0,
      max: 100000,
      step: 1,
      placement: { tabId: 'twostage', sectionId: 'bottom-layers', cardId: 'bottom-layers-card', order: 30 },
      metadataPath: 'material.bottomRetractSpeed2MmMin',
    },
    {
      key: 'bottomRetractSpeedMmMin',
      label: 'Z Retract Speed Step 2 (mm/min)',
      kind: 'number' as const,
      defaultValue: 180,
      min: 0,
      max: 100000,
      step: 1,
      placement: { tabId: 'twostage', sectionId: 'bottom-layers', cardId: 'bottom-layers-card', order: 31 },
      metadataPath: 'material.bottomRetractSpeedMmMin',
    },
  ],
} as const;

const ANYCUBIC_AZF_MATERIAL_SETTINGS: PluginLocalMaterialSettingsAdapterContract = {
  outputFormat: ANYCUBIC_AZF_FORMAT_DEFINITION.outputFormat,
  ...ANYCUBIC_MATERIAL_SETTINGS_BASE,
};

const ANYCUBIC_AFF_MATERIAL_SETTINGS: PluginLocalMaterialSettingsAdapterContract = {
  outputFormat: ANYCUBIC_AFF_FORMAT_DEFINITION.outputFormat,
  ...ANYCUBIC_MATERIAL_SETTINGS_BASE,
};

// ─── Plugin definition ──────────────────────────────────────────────

export const ANYCUBIC_COMPLEX_PLUGIN_DEFINITION: ComplexPluginDefinition = {
  id: 'anycubic',
  manifest: ANYCUBIC_PLUGIN_MANIFEST,
  capabilities: {
    networkOperations: false,
    uploadWithProgress: false,
    slicerEncoder: true,
    tauriRuntimePlugin: false,
  },
  slicingFormatsByOutput: {
    // AFF format — Photon / Photon Mono series
    '.pws': ANYCUBIC_AFF_FORMAT_DEFINITION,
    '.pw0': ANYCUBIC_AFF_FORMAT_DEFINITION,
    '.pwx': ANYCUBIC_AFF_FORMAT_DEFINITION,
    '.dlp': ANYCUBIC_AFF_FORMAT_DEFINITION,
    '.dl2p': ANYCUBIC_AFF_FORMAT_DEFINITION,
    '.pwmx': ANYCUBIC_AFF_FORMAT_DEFINITION,
    '.pmx2': ANYCUBIC_AFF_FORMAT_DEFINITION,
    '.pwmb': ANYCUBIC_AFF_FORMAT_DEFINITION,
    '.px6s': ANYCUBIC_AFF_FORMAT_DEFINITION,
    '.pwmo': ANYCUBIC_AFF_FORMAT_DEFINITION,
    '.pm3n': ANYCUBIC_AFF_FORMAT_DEFINITION,
    '.pm4n': ANYCUBIC_AFF_FORMAT_DEFINITION,
    '.pwms': ANYCUBIC_AFF_FORMAT_DEFINITION,
    '.pwma': ANYCUBIC_AFF_FORMAT_DEFINITION,
    '.pmsq': ANYCUBIC_AFF_FORMAT_DEFINITION,
    '.pm3': ANYCUBIC_AFF_FORMAT_DEFINITION,
    '.pm3m': ANYCUBIC_AFF_FORMAT_DEFINITION,
    '.pm3r': ANYCUBIC_AFF_FORMAT_DEFINITION,
    '.pm5': ANYCUBIC_AFF_FORMAT_DEFINITION,
    '.pm5s': ANYCUBIC_AFF_FORMAT_DEFINITION,
    '.m5sp': ANYCUBIC_AFF_FORMAT_DEFINITION,
    '.pwc': ANYCUBIC_AFF_FORMAT_DEFINITION,
    // AZF format — Photon Mono M7 series and Mono 4 Ultra
    '.pm4u': ANYCUBIC_AZF_FORMAT_DEFINITION,
    '.pm7': ANYCUBIC_AZF_FORMAT_DEFINITION,
    '.pm7m': ANYCUBIC_AZF_FORMAT_DEFINITION,
    '.pwsz': ANYCUBIC_AZF_FORMAT_DEFINITION,
  },
  localMaterialSettingsByOutput: {
    // AFF extensions
    '.pws': ANYCUBIC_AFF_MATERIAL_SETTINGS,
    '.pw0': ANYCUBIC_AFF_MATERIAL_SETTINGS,
    '.pwx': ANYCUBIC_AFF_MATERIAL_SETTINGS,
    '.dlp': ANYCUBIC_AFF_MATERIAL_SETTINGS,
    '.dl2p': ANYCUBIC_AFF_MATERIAL_SETTINGS,
    '.pwmx': ANYCUBIC_AFF_MATERIAL_SETTINGS,
    '.pmx2': ANYCUBIC_AFF_MATERIAL_SETTINGS,
    '.pwmb': ANYCUBIC_AFF_MATERIAL_SETTINGS,
    '.px6s': ANYCUBIC_AFF_MATERIAL_SETTINGS,
    '.pwmo': ANYCUBIC_AFF_MATERIAL_SETTINGS,
    '.pm3n': ANYCUBIC_AFF_MATERIAL_SETTINGS,
    '.pm4n': ANYCUBIC_AFF_MATERIAL_SETTINGS,
    '.pwms': ANYCUBIC_AFF_MATERIAL_SETTINGS,
    '.pwma': ANYCUBIC_AFF_MATERIAL_SETTINGS,
    '.pmsq': ANYCUBIC_AFF_MATERIAL_SETTINGS,
    '.pm3': ANYCUBIC_AFF_MATERIAL_SETTINGS,
    '.pm3m': ANYCUBIC_AFF_MATERIAL_SETTINGS,
    '.pm3r': ANYCUBIC_AFF_MATERIAL_SETTINGS,
    '.pm5': ANYCUBIC_AFF_MATERIAL_SETTINGS,
    '.pm5s': ANYCUBIC_AFF_MATERIAL_SETTINGS,
    '.m5sp': ANYCUBIC_AFF_MATERIAL_SETTINGS,
    '.pwc': ANYCUBIC_AFF_MATERIAL_SETTINGS,
    // AZF extensions
    '.pm4u': ANYCUBIC_AZF_MATERIAL_SETTINGS,
    '.pm7': ANYCUBIC_AZF_MATERIAL_SETTINGS,
    '.pm7m': ANYCUBIC_AZF_MATERIAL_SETTINGS,
    '.pwsz': ANYCUBIC_AZF_MATERIAL_SETTINGS,
  },
};

export default ANYCUBIC_COMPLEX_PLUGIN_DEFINITION;
